"""Regenerate src/pumpdump/data/common_words.txt.

Bare uppercase tokens like "ON", "PUMP" or "MOON" are real ticker symbols but
are usually just English words. The extractor only accepts a bare token as a
ticker when its lowercase form is NOT a common English word; otherwise the
poster has to write it as a cashtag ($PUMP) or with an exchange prefix.

"Common" = wordfreq Zipf frequency >= 4.0 (about 10 uses per million words),
ASCII letters only, 2-5 characters. Run once by hand; needs `pip install
wordfreq` (dev-only, not a runtime dependency).
"""

from pathlib import Path

from wordfreq import top_n_list, zipf_frequency

ZIPF_MIN = 4.0
OUT = Path(__file__).resolve().parents[1] / "src" / "pumpdump" / "data" / "common_words.txt"


def main() -> None:
    words = sorted(
        {
            w
            for w in top_n_list("en", 200_000)
            if w.isascii() and w.isalpha() and 2 <= len(w) <= 5 and zipf_frequency(w, "en") >= ZIPF_MIN
        }
    )
    header = f"# English words (2-5 letters) with wordfreq Zipf >= {ZIPF_MIN}; generated by scripts/gen_common_words.py\n"
    OUT.write_text(header + "\n".join(words) + "\n")
    print(f"wrote {len(words)} words to {OUT}")


if __name__ == "__main__":
    main()
